### PR TITLE
Fix label for element template replace menu entries

### LINKED ISSUE #220: Element template names are not displayed in replace menu entries
__Describe the Bug__

Element template names are not displayed in replace menu entries.

Screenshot 2022-12-14 at 11 42 57

__Steps to Reproduce__

1. disable connectors extension 
2. open replace menu for a service task
3. see that template names are not displayed

__Expected Behavior__

Element template names should be displayed as the entry label

### PR DESCRIPTION
**Pull request by smbea**
Closes #220 

Following https://github.com/camunda/camunda-bpmn-js/issues/220#issuecomment-1350950639, I removed the connectors extension from the base test case and added some integration tests for it.

### CODE REVIEW

File: test/camunda-cloud/ElementTemplatesReplaceProviderSpec.js [hunk 1]
```diff
@@ -323,6 +326,63 @@ describe('<ElementTemplatesReplaceProvider>', function() {
...
+        },
+      }
+    ));
+
+    beforeEach(inject(function(elementTemplates) {
+      elementTemplates.set(templates);
+    }));
+
+
+    it('templates are not duplicated', inject(function(elementRegistry, selection, replaceMenu, changeMenu) {
```
Comment (nikku) [inline test/camunda-cloud/ElementTemplatesReplaceProviderSpec.js:348]: You could make this part of the cloud [`ModelerSpec`](https://github.com/camunda/camunda-bpmn-js/blob/main/test/camunda-cloud/ModelerSpec.js). I'd suggest to create a `start:xxx` script, too so the integration can be tested easily manually (cf. [existing](https://github.com/camunda/camunda-bpmn-js/blob/main/test/camunda-cloud/ModelerSpec.js#L137) cloud version).

File: test/camunda-cloud/ModelerSpec.js [hunk 2]
```diff
@@ -108,12 +107,6 @@ describe('<CamundaCloudModeler>', function() {
       keyboard: {
         bindTo: document
       },
-      connectorsExtension: {
-        appendAnything: true
```
Comment (nikku) [inline test/camunda-cloud/ModelerSpec.js:112]: Let us add the [`@bpmn-io/element-template-chooser`](https://github.com/bpmn-io/element-template-chooser) here so the examples remain usable (i.e. I can select element templates from the properties panel).

File: test/camunda-cloud/ModelerSpec.js [hunk 3]
```diff
@@ -222,4 +236,83 @@ describe('<CamundaCloudModeler>', function() {
 
   });
 
+
+  describe('integration with connectors extension', function() {
```
Comment (nikku) [inline test/camunda-cloud/ModelerSpec.js:240]: :heart:

File: test/camunda-cloud/ModelerSpec.js [hunk 4]
```diff
@@ -222,4 +236,83 @@ describe('<CamundaCloudModeler>', function() {
...
+      // then
+      const entries = domQueryAll('[data-entry-id^="replace.template-"]');
+      expect(entries).to.have.length(5);
+
+    }));
+
+
+    it('unlink template option is not duplicated', inject(function(elementRegistry, replaceMenu, elementTemplates) {
+
+      // given
```
Comment (nikku) [inline test/camunda-cloud/ModelerSpec.js:300]: Awesome coverage ensuring we don't mess it up in the transition phase. :star:
